Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader (const GLchar *vertexPath, const GLchar *fragmentPath)
void install ()
void uninstall ()
Public Attributes
GLuint Program
Detailed Description
Definition at line 9 of file Shader.h.
Constructor & Destructor Documentation
Shader()
Shader::Shader (const GLchar * vertexPath, const GLchar * fragmentPath)
Definition at line 9 of file Shader.cpp.
References Program.
Member Function Documentation
install()
void Shader::install ()
Definition at line 98 of file Shader.cpp.
References Program.
Referenced by SICAD::setBackground(), SICAD::setProjectionMatrix(), and SICAD::superimpose().
uninstall()
void Shader::uninstall ()
Definition at line 104 of file Shader.cpp.
Referenced by SICAD::setBackground(), SICAD::setProjectionMatrix(), and SICAD::superimpose().
Member Data Documentation
Program
GLuint Shader::Program
Definition at line 22 of file Shader.h.
Referenced by install(), SICAD::setBackground(), SICAD::setProjectionMatrix(), Shader(), and SICAD::superimpose().
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/include/SuperimposeMesh/Shader.h
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/src/Shader.cpp