SISkeleton Class Reference
#include <SISkeleton.h>
Public Types
typedef std::vector< double > ModelPose
typedef std::multimap< std::string, ModelPose > ModelPoseContainer
typedef std::pair< std::string, ModelPose > ModelPoseContainerElement
Public Member Functions
SISkeleton ()
SISkeleton (const float cam_fx, const float cam_fy, const float cam_cx, const float cam_cy)
~SISkeleton ()
bool superimpose (const ModelPoseContainer &objpos_map, const double *cam_x, const double *cam_o, cv::Mat &img) override
bool setProjectionMatrix (const float cam_fx, const float cam_fy, const float cam_cx, const float cam_cy)
Protected Member Functions
glm::vec2 getWorldToPixel (const double *world_point)
Private Attributes
const std::string log_ID_ = `[SI-Skeleton]`
std::list< std::string > hand_part_
glm::mat3 projection_
glm::mat3 root_to_eye_
glm::vec3 cam_pos_
Detailed Description
Definition at line 12 of file SISkeleton.h.
Member Typedef Documentation
ModelPose
typedef std::vector<double> Superimpose::ModelPose [inherited]
Definition at line 16 of file Superimpose.h.
ModelPoseContainer
typedef std::multimap<std::string, ModelPose> Superimpose::ModelPoseContainer [inherited]
Definition at line 17 of file Superimpose.h.
ModelPoseContainerElement
typedef std::pair<std::string, ModelPose> Superimpose::ModelPoseContainerElement [inherited]
Definition at line 18 of file Superimpose.h.
Constructor & Destructor Documentation
SISkeleton() [1/2]
SISkeleton::SISkeleton ()
Definition at line 11 of file SISkeleton.cpp.
SISkeleton() [2/2]
SISkeleton::SISkeleton (const float cam_fx, const float cam_fy, const float cam_cx, const float cam_cy)
Definition at line 17 of file SISkeleton.cpp.
References log_ID_, and setProjectionMatrix().
 SISkeleton()
SISkeleton::~SISkeleton ()
Definition at line 26 of file SISkeleton.cpp.
Member Function Documentation
getWorldToPixel()
glm::vec2 SISkeleton::getWorldToPixel (const double * world_point) [protected]
Definition at line 76 of file SISkeleton.cpp.
References cam_pos_, projection_, and root_to_eye_.
Referenced by superimpose().
setProjectionMatrix()
bool SISkeleton::setProjectionMatrix (const float cam_fx, const float cam_fy, const float cam_cx, const float cam_cy)
Definition at line 60 of file SISkeleton.cpp.
References projection_.
Referenced by SISkeleton().
superimpose()
bool SISkeleton::superimpose (const ModelPoseContainer & objpos_map, const double * cam_x, const double * cam_o, cv::Mat & img) [override], [virtual]
Implements Superimpose.
Definition at line 30 of file SISkeleton.cpp.
References cam_pos_, getWorldToPixel(), hand_part_, and root_to_eye_.
Member Data Documentation
cam_pos_
glm::vec3 SISkeleton::cam_pos_ [private]
Definition at line 34 of file SISkeleton.h.
Referenced by getWorldToPixel(), and superimpose().
hand_part_
std::list<std::string> SISkeleton::hand_part_ [private]
Definition at line 31 of file SISkeleton.h.
Referenced by superimpose().
log_ID_
const std::string SISkeleton::log_ID_ = `[SI-Skeleton]` [private]
Definition at line 29 of file SISkeleton.h.
Referenced by SISkeleton().
projection_
glm::mat3 SISkeleton::projection_ [private]
Definition at line 32 of file SISkeleton.h.
Referenced by getWorldToPixel(), and setProjectionMatrix().
root_to_eye_
glm::mat3 SISkeleton::root_to_eye_ [private]
Definition at line 33 of file SISkeleton.h.
Referenced by getWorldToPixel(), and superimpose().
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/include/SuperimposeMesh/SISkeleton.h
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/src/SISkeleton.cpp