SICAD Class Reference
A Superimpose derived class to superimpose mesh models on top of images.
#include <SICAD.h>
Public Types
enum MIPMaps { MIPMaps::nearest,
MIPMaps::linear
 }
typedef std::unordered_map< std::string, std::string > ModelPathContainer
typedef std::pair< std::string, std::string > ModelPathElement
typedef std::unordered_map< std::string, Model * > ModelContainer
typedef std::pair< std::string, Model * > ModelElement
typedef std::vector< double > ModelPose
typedef std::multimap< std::string, ModelPose > ModelPoseContainer
typedef std::pair< std::string, ModelPose > ModelPoseContainerElement
Public Member Functions
SICAD ()
SICAD (const ModelPathContainer &objfile_map, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::vector< float > &ogl_to_cam, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::string &shader_folder, const bool window_visible)
SICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::vector< float > &ogl_to_cam, const std::string &shader_folder, const bool window_visible)
Create a SICAD object with a dedicated OpenGL window and context.
bool initSICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::vector< float > &ogl_to_cam, const std::string &shader_folder, const bool window_visible)
bool initSICAD (const ModelPathContainer &objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::vector< float > &ogl_to_cam, const std::string &shader_folder, const bool window_visible)
virtual ~SICAD ()
bool getOglWindowShouldClose ()
void setOglWindowShouldClose (bool should_close)
bool superimpose (const ModelPoseContainer &objpos_map, const double *cam_x, const double *cam_o, cv::Mat &img) override
Superimpose one of the mesh models loaded during SICAD object construction in a given pose from a particular camera viewpoint.
virtual bool superimpose (const std::vector< ModelPoseContainer > &objpos_multimap, const double *cam_x, const double *cam_o, cv::Mat &img)
virtual bool superimpose (const ModelPoseContainer &objpos_map, const double *cam_x, const double *cam_o, cv::Mat &img, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy)
virtual bool superimpose (const std::vector< ModelPoseContainer > &objpos_multimap, const double *cam_x, const double *cam_o, cv::Mat &img, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy)
bool setProjectionMatrix (const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy)
bool getBackgroundOpt () const
void setBackgroundOpt (bool show_background)
GLenum getWireframeOpt () const
void setWireframeOpt (bool show_mesh_wires)
MIPMaps getMipmapsOpt () const
int getTilesNumber () const
int getTilesRows () const
int getTilesCols () const
Private Member Functions
bool initOGL (const GLsizei width, const GLsizei height, const GLint num_viewports, const bool window_visibile)
glm::mat4 getViewTransformationMatrix (const double *cam_x, const double *cam_o)
void pollOrPostEvent ()
void setBackground (cv::Mat &img)
void setWireframe (GLenum mode)
void factorize_int (const GLsizei area, const GLsizei width_limit, const GLsizei height_limit, GLsizei &width, GLsizei &height)
Static Private Member Functions
static void callbackKeypress (GLFWwindow *window, int key, int scancode, int action, int mode)
Private Attributes
bool is_initialized_ = false
bool has_proj_matrix_ = false
const std::string log_ID_ = `[SI-CAD]`
GLFWwindow * window_ = nullptr
GLint tiles_num_ = 0
GLsizei tiles_cols_ = 0
GLsizei tiles_rows_ = 0
GLsizei image_width_ = 0
GLsizei image_height_ = 0
glm::mat3 ogl_to_cam_ = glm::mat3(1.0f)
GLsizei framebuffer_width_ = 0
GLsizei framebuffer_height_ = 0
GLsizei render_img_width_ = 0
GLsizei render_img_height_ = 0
const GLfloat near_ = 0.001f
const GLfloat far_ = 1000.0f
std::thread::id main_thread_id_
bool show_background_ = false
GLenum show_mesh_mode_ = GL_FILL
MIPMaps mesh_mmaps_ = MIPMaps::nearest
Shader * shader_background_ = nullptr
Shader * shader_cad_ = nullptr
Shader * shader_frame_ = nullptr
ModelContainer model_obj_
GLuint fbo_
GLuint texture_color_buffer_
GLuint texture_depth_buffer_
GLuint texture_background_
GLuint vao_background_
GLuint ebo_background_
GLuint vbo_background_
GLuint vao_frame_
GLuint vbo_frame_
glm::mat4 back_proj_
glm::mat4 projection_
Static Private Attributes
static int class_counter_ = 0
static GLsizei renderbuffer_size_ = 0
Detailed Description
A Superimpose derived class to superimpose mesh models on top of images.
Definition at line 21 of file SICAD.h.
Member Typedef Documentation
ModelContainer
typedef std::unordered_map<std::string, Model*> SICAD::ModelContainer
Definition at line 27 of file SICAD.h.
ModelElement
typedef std::pair<std::string, Model*> SICAD::ModelElement
Definition at line 28 of file SICAD.h.
ModelPathContainer
typedef std::unordered_map<std::string, std::string> SICAD::ModelPathContainer
Definition at line 24 of file SICAD.h.
ModelPathElement
typedef std::pair<std::string, std::string> SICAD::ModelPathElement
Definition at line 25 of file SICAD.h.
ModelPose
typedef std::vector<double> Superimpose::ModelPose [inherited]
Definition at line 16 of file Superimpose.h.
ModelPoseContainer
typedef std::multimap<std::string, ModelPose> Superimpose::ModelPoseContainer [inherited]
Definition at line 17 of file Superimpose.h.
ModelPoseContainerElement
typedef std::pair<std::string, ModelPose> Superimpose::ModelPoseContainerElement [inherited]
Definition at line 18 of file Superimpose.h.
Member Enumeration Documentation
MIPMaps
enum SICAD::MIPMaps [strong]
Enumerator
nearest
linear
Definition at line 30 of file SICAD.h.
Constructor & Destructor Documentation
SICAD() [1/9]
SICAD::SICAD ()
Definition at line 20 of file SICAD.cpp.
SICAD() [2/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const bool window_visible)
Definition at line 23 of file SICAD.cpp.
SICAD() [3/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const std::string & shader_folder, const bool window_visible)
Definition at line 33 of file SICAD.cpp.
SICAD() [4/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const std::string & shader_folder, const bool window_visible)
Definition at line 44 of file SICAD.cpp.
SICAD() [5/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::string & shader_folder, const bool window_visible)
Definition at line 56 of file SICAD.cpp.
SICAD() [6/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::vector< float > & ogl_to_cam, const std::string & shader_folder, const bool window_visible)
Definition at line 69 of file SICAD.cpp.
References initSICAD().
SICAD() [7/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const std::string & shader_folder, const bool window_visible)
Definition at line 85 of file SICAD.cpp.
SICAD() [8/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::string & shader_folder, const bool window_visible)
Definition at line 102 of file SICAD.cpp.
SICAD() [9/9]
SICAD::SICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::vector< float > & ogl_to_cam, const std::string & shader_folder, const bool window_visible)
Create a SICAD object with a dedicated OpenGL window and context.
For the SICAD object to work properly, four shaders are needed. Further, their name must be as follows:
shader_model.vert for the model vertex shader
shader_model.frag for the model fragment shader
shader_background.vert for the background vertex shader
shader_background.frag for the background fragment shader
Parameters
objfile_map a (tag, path) container to associate a 'tag' to the mesh file specified in 'path'.
cam_width camera or image width.
cam_height camera or image height.
cam_fx focal length along the x axis in pixels.
cam_fy focal length along the y axis in pixels.
num_images number of images to render (using glScissor) in the same window and context.
ogl_to_cam a 7 component pose vector, (x, y, z) position and a (ux, uy, uz, theta) axis-angle orientation, defining a camera rotation to be applied to the OpenGL camera.
shader_folder folder path containing four shaders, two for the background and two for the mesh.
window_visible true to show the rendering window, false to perform off-screen rendering.
Definition at line 120 of file SICAD.cpp.
References log_ID_, and setProjectionMatrix().
 SICAD()
SICAD::~SICAD () [virtual]
Definition at line 140 of file SICAD.cpp.
References class_counter_, ebo_background_, fbo_, log_ID_, model_obj_, shader_background_, shader_cad_, texture_background_, texture_color_buffer_, texture_depth_buffer_, vao_background_, vao_frame_, vbo_background_, vbo_frame_, and window_.
Member Function Documentation
callbackKeypress()
static void SICAD::callbackKeypress (GLFWwindow * window, int key, int scancode, int action, int mode) [static], [private]
factorize_int()
void SICAD::factorize_int (const GLsizei area, const GLsizei width_limit, const GLsizei height_limit, GLsizei & width, GLsizei & height) [private]
Definition at line 942 of file SICAD.cpp.
Referenced by initOGL().
getBackgroundOpt()
bool SICAD::getBackgroundOpt () const
Definition at line 834 of file SICAD.cpp.
References show_background_.
Referenced by superimpose().
getMipmapsOpt()
SICAD::MIPMaps SICAD::getMipmapsOpt () const
Definition at line 853 of file SICAD.cpp.
References mesh_mmaps_.
Referenced by setBackground().
getOglWindowShouldClose()
bool SICAD::getOglWindowShouldClose ()
Definition at line 500 of file SICAD.cpp.
References is_initialized_, and window_.
getTilesCols()
int SICAD::getTilesCols () const
Definition at line 871 of file SICAD.cpp.
References tiles_cols_.
getTilesNumber()
int SICAD::getTilesNumber () const
Definition at line 859 of file SICAD.cpp.
References tiles_cols_, and tiles_rows_.
getTilesRows()
int SICAD::getTilesRows () const
Definition at line 865 of file SICAD.cpp.
References tiles_rows_.
getViewTransformationMatrix()
glm::mat4 SICAD::getViewTransformationMatrix (const double * cam_x, const double * cam_o) [private]
Definition at line 877 of file SICAD.cpp.
References ogl_to_cam_.
Referenced by superimpose().
getWireframeOpt()
GLenum SICAD::getWireframeOpt () const
Definition at line 847 of file SICAD.cpp.
References show_mesh_mode_.
Referenced by superimpose().
initOGL()
bool SICAD::initOGL (const GLsizei width, const GLsizei height, const GLint num_viewports, const bool window_visibile) [private]
Definition at line 413 of file SICAD.cpp.
References factorize_int(), framebuffer_height_, framebuffer_width_, image_height_, image_width_, log_ID_, main_thread_id_, render_img_height_, render_img_width_, renderbuffer_size_, tiles_cols_, tiles_num_, tiles_rows_, and window_.
Referenced by initSICAD().
initSICAD() [1/2]
bool SICAD::initSICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLint num_images, const std::vector< float > & ogl_to_cam, const std::string & shader_folder, const bool window_visible)
Definition at line 181 of file SICAD.cpp.
References back_proj_, class_counter_, ebo_background_, far_, fbo_, framebuffer_height_, framebuffer_width_, initOGL(), is_initialized_, log_ID_, model_obj_, ogl_to_cam_, shader_background_, shader_cad_, shader_frame_, texture_background_, texture_color_buffer_, texture_depth_buffer_, vao_background_, vao_frame_, vbo_background_, vbo_frame_, and window_.
Referenced by initSICAD(), and SICAD().
initSICAD() [2/2]
bool SICAD::initSICAD (const ModelPathContainer & objfile_map, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy, const GLint num_images, const std::vector< float > & ogl_to_cam, const std::string & shader_folder, const bool window_visible)
Definition at line 389 of file SICAD.cpp.
References initSICAD(), log_ID_, and setProjectionMatrix().
pollOrPostEvent()
void SICAD::pollOrPostEvent () [private]
Definition at line 892 of file SICAD.cpp.
References main_thread_id_.
Referenced by setOglWindowShouldClose(), and superimpose().
setBackground()
void SICAD::setBackground (cv::Mat & img) [private]
Definition at line 901 of file SICAD.cpp.
References back_proj_, getMipmapsOpt(), Shader::install(), linear, nearest, Shader::Program, shader_background_, texture_background_, Shader::uninstall(), and vao_background_.
Referenced by superimpose().
setBackgroundOpt()
void SICAD::setBackgroundOpt (bool show_background)
Definition at line 828 of file SICAD.cpp.
References show_background_.
Referenced by main().
setOglWindowShouldClose()
void SICAD::setOglWindowShouldClose (bool should_close)
Definition at line 512 of file SICAD.cpp.
References is_initialized_, pollOrPostEvent(), and window_.
setProjectionMatrix()
bool SICAD::setProjectionMatrix (const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy)
Definition at line 774 of file SICAD.cpp.
References far_, has_proj_matrix_, Shader::install(), is_initialized_, near_, Shader::Program, projection_, shader_cad_, shader_frame_, Shader::uninstall(), and window_.
Referenced by initSICAD(), SICAD(), and superimpose().
setWireframe()
void SICAD::setWireframe (GLenum mode) [private]
Definition at line 936 of file SICAD.cpp.
Referenced by superimpose().
setWireframeOpt()
void SICAD::setWireframeOpt (bool show_mesh_wires)
Definition at line 840 of file SICAD.cpp.
References show_mesh_mode_.
superimpose() [1/4]
bool SICAD::superimpose (const ModelPoseContainer & objpos_map, const double * cam_x, const double * cam_o, cv::Mat & img) [override], [virtual]
Superimpose one of the mesh models loaded during SICAD object construction in a given pose from a particular camera viewpoint.
If the size of cv::Mat img is not correct to store the result of the superimposition process, it is automatically resized.
Note
If cv::Mat img is a background image it must be of size cam_width*cam_height, as specified during object construction, and the SICAD::setBackgroundOpt(bool show_background) must have been evoked with true.
Parameters
objpos_map a (tag, pose) container to associate a 7 component 'pose', (x, y, z) position and a (ux, uy, uz, theta) axis-angle orientation, to a mesh with tag 'tag'.
cam_x (x, y, z) position
cam_o (ux, uy, uz, theta) axis-angle orientation
img an image where the result of the superimposition is stored
Returns
true upon success, false otherswise.
Implements Superimpose.
Definition at line 526 of file SICAD.cpp.
References fbo_, framebuffer_height_, framebuffer_width_, getBackgroundOpt(), getViewTransformationMatrix(), getWireframeOpt(), has_proj_matrix_, Shader::install(), is_initialized_, model_obj_, pollOrPostEvent(), Shader::Program, render_img_height_, render_img_width_, setBackground(), setWireframe(), shader_cad_, shader_frame_, tiles_cols_, tiles_rows_, Shader::uninstall(), vao_frame_, and window_.
Referenced by main(), and superimpose().
superimpose() [2/4]
bool SICAD::superimpose (const std::vector< ModelPoseContainer > & objpos_multimap, const double * cam_x, const double * cam_o, cv::Mat & img) [virtual]
Definition at line 626 of file SICAD.cpp.
References fbo_, framebuffer_height_, framebuffer_width_, getBackgroundOpt(), getViewTransformationMatrix(), getWireframeOpt(), has_proj_matrix_, Shader::install(), is_initialized_, model_obj_, pollOrPostEvent(), Shader::Program, render_img_height_, render_img_width_, setBackground(), setWireframe(), shader_cad_, shader_frame_, tiles_cols_, tiles_num_, tiles_rows_, Shader::uninstall(), vao_frame_, and window_.
superimpose() [3/4]
bool SICAD::superimpose (const ModelPoseContainer & objpos_map, const double * cam_x, const double * cam_o, cv::Mat & img, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy) [virtual]
Definition at line 740 of file SICAD.cpp.
References is_initialized_, setProjectionMatrix(), and superimpose().
superimpose() [4/4]
bool SICAD::superimpose (const std::vector< ModelPoseContainer > & objpos_multimap, const double * cam_x, const double * cam_o, cv::Mat & img, const GLsizei cam_width, const GLsizei cam_height, const GLfloat cam_fx, const GLfloat cam_fy, const GLfloat cam_cx, const GLfloat cam_cy) [virtual]
Definition at line 757 of file SICAD.cpp.
References is_initialized_, setProjectionMatrix(), and superimpose().
Member Data Documentation
back_proj_
glm::mat4 SICAD::back_proj_ [private]
Definition at line 205 of file SICAD.h.
Referenced by initSICAD(), and setBackground().
class_counter_
int SICAD::class_counter_ = 0 [static], [private]
Definition at line 167 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
ebo_background_
GLuint SICAD::ebo_background_ [private]
Definition at line 201 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
far_
const GLfloat SICAD::far_ = 1000.0f [private]
Definition at line 185 of file SICAD.h.
Referenced by initSICAD(), and setProjectionMatrix().
fbo_
GLuint SICAD::fbo_ [private]
Definition at line 196 of file SICAD.h.
Referenced by initSICAD(), superimpose(), and ~SICAD().
framebuffer_height_
GLsizei SICAD::framebuffer_height_ = 0 [private]
Definition at line 181 of file SICAD.h.
Referenced by initOGL(), initSICAD(), and superimpose().
framebuffer_width_
GLsizei SICAD::framebuffer_width_ = 0 [private]
Definition at line 180 of file SICAD.h.
Referenced by initOGL(), initSICAD(), and superimpose().
has_proj_matrix_
bool SICAD::has_proj_matrix_ = false [private]
Definition at line 164 of file SICAD.h.
Referenced by setProjectionMatrix(), and superimpose().
image_height_
GLsizei SICAD::image_height_ = 0 [private]
Definition at line 178 of file SICAD.h.
Referenced by initOGL().
image_width_
GLsizei SICAD::image_width_ = 0 [private]
Definition at line 177 of file SICAD.h.
Referenced by initOGL().
is_initialized_
bool SICAD::is_initialized_ = false [private]
Definition at line 163 of file SICAD.h.
Referenced by getOglWindowShouldClose(), initSICAD(), setOglWindowShouldClose(), setProjectionMatrix(), and superimpose().
log_ID_
const std::string SICAD::log_ID_ = `[SI-CAD]` [private]
Definition at line 171 of file SICAD.h.
Referenced by initOGL(), initSICAD(), SICAD(), and ~SICAD().
main_thread_id_
std::thread::id SICAD::main_thread_id_ [private]
Definition at line 187 of file SICAD.h.
Referenced by initOGL(), and pollOrPostEvent().
mesh_mmaps_
MIPMaps SICAD::mesh_mmaps_ = MIPMaps::nearest [private]
Definition at line 191 of file SICAD.h.
Referenced by getMipmapsOpt().
model_obj_
ModelContainer SICAD::model_obj_ [private]
Definition at line 195 of file SICAD.h.
Referenced by initSICAD(), superimpose(), and ~SICAD().
near_
const GLfloat SICAD::near_ = 0.001f [private]
Definition at line 184 of file SICAD.h.
Referenced by setProjectionMatrix().
ogl_to_cam_
glm::mat3 SICAD::ogl_to_cam_ = glm::mat3(1.0f) [private]
Definition at line 179 of file SICAD.h.
Referenced by getViewTransformationMatrix(), and initSICAD().
projection_
glm::mat4 SICAD::projection_ [private]
Definition at line 206 of file SICAD.h.
Referenced by setProjectionMatrix().
render_img_height_
GLsizei SICAD::render_img_height_ = 0 [private]
Definition at line 183 of file SICAD.h.
Referenced by initOGL(), and superimpose().
render_img_width_
GLsizei SICAD::render_img_width_ = 0 [private]
Definition at line 182 of file SICAD.h.
Referenced by initOGL(), and superimpose().
renderbuffer_size_
GLsizei SICAD::renderbuffer_size_ = 0 [static], [private]
Definition at line 168 of file SICAD.h.
Referenced by initOGL().
shader_background_
Shader* SICAD::shader_background_ = nullptr [private]
Definition at line 192 of file SICAD.h.
Referenced by initSICAD(), setBackground(), and ~SICAD().
shader_cad_
Shader* SICAD::shader_cad_ = nullptr [private]
Definition at line 193 of file SICAD.h.
Referenced by initSICAD(), setProjectionMatrix(), superimpose(), and ~SICAD().
shader_frame_
Shader* SICAD::shader_frame_ = nullptr [private]
Definition at line 194 of file SICAD.h.
Referenced by initSICAD(), setProjectionMatrix(), and superimpose().
show_background_
bool SICAD::show_background_ = false [private]
Definition at line 189 of file SICAD.h.
Referenced by getBackgroundOpt(), and setBackgroundOpt().
show_mesh_mode_
GLenum SICAD::show_mesh_mode_ = GL_FILL [private]
Definition at line 190 of file SICAD.h.
Referenced by getWireframeOpt(), and setWireframeOpt().
texture_background_
GLuint SICAD::texture_background_ [private]
Definition at line 199 of file SICAD.h.
Referenced by initSICAD(), setBackground(), and ~SICAD().
texture_color_buffer_
GLuint SICAD::texture_color_buffer_ [private]
Definition at line 197 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
texture_depth_buffer_
GLuint SICAD::texture_depth_buffer_ [private]
Definition at line 198 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
tiles_cols_
GLsizei SICAD::tiles_cols_ = 0 [private]
Definition at line 175 of file SICAD.h.
Referenced by getTilesCols(), getTilesNumber(), initOGL(), and superimpose().
tiles_num_
GLint SICAD::tiles_num_ = 0 [private]
Definition at line 174 of file SICAD.h.
Referenced by initOGL(), and superimpose().
tiles_rows_
GLsizei SICAD::tiles_rows_ = 0 [private]
Definition at line 176 of file SICAD.h.
Referenced by getTilesNumber(), getTilesRows(), initOGL(), and superimpose().
vao_background_
GLuint SICAD::vao_background_ [private]
Definition at line 200 of file SICAD.h.
Referenced by initSICAD(), setBackground(), and ~SICAD().
vao_frame_
GLuint SICAD::vao_frame_ [private]
Definition at line 203 of file SICAD.h.
Referenced by initSICAD(), superimpose(), and ~SICAD().
vbo_background_
GLuint SICAD::vbo_background_ [private]
Definition at line 202 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
vbo_frame_
GLuint SICAD::vbo_frame_ [private]
Definition at line 204 of file SICAD.h.
Referenced by initSICAD(), and ~SICAD().
window_
GLFWwindow* SICAD::window_ = nullptr [private]
Definition at line 173 of file SICAD.h.
Referenced by getOglWindowShouldClose(), initOGL(), initSICAD(), setOglWindowShouldClose(), setProjectionMatrix(), superimpose(), and ~SICAD().
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/include/SuperimposeMesh/SICAD.h
C:/Users/cfantacci/GitHub/superimpose-mesh-lib/src/SuperimposeMesh/src/SICAD.cpp